### ISSUE TITLE
Question: Controlling volume of external audio system

### ISSUE THREAD

**Issue by jarrodek** [senzil/cec-monitor#11]
I'm trying to figure out flow of the CEC (today I've started doing anything with it). So far I'm quite lost if it comes to controlling audio systems.

The following command is turning of my audio system (sound bar):

```javascript
monitor.WriteMessage(CEC.LogicalAddress.BROADCAST, CEC.LogicalAddress.AUDIOSYSTEM, CEC.Opcode.STANDBY);
```

however I can't find the right combination to do the opposite - turn the audio on. Is the source the broadcast? If yes then audio system id destination. Bu I can't find a `Opcode` to put in the command. Could you please help me figure it out? And then how to control the volume of audio system? By mocking remote keys? Or there's a command for that?

**Comment by pablodgonzalez** [comment]
HI @jarrodek,
first I recommend you to view http://www.cec-o-matic.com/. This web is for cec 1.3a but you will get the most important opcodes.
second you must known the audio system is unique for and HDMI network, so you must use system audio opcodes in this case CEC.Opcode.SET_SYSTEM_AUDIO_MODE with value CEC.SystemAudioStatus.ON
```javascript
monitor.WriteMessage(CEC.LogicalAddress.BROADCAST, CEC.LogicalAddress.AUDIOSYSTEM, CEC.Opcode.SET_SYSTEM_AUDIO_MODE, CEC.SystemAudioStatus.ON);
```
For volume control you can
A) use WriteRawMessage with volup voldown (cec-client commands)
```javascript
monitor.WriteRawMessage('volup')
monitor.WriteRawMessage('voldown')
```
B) do it like cec-client do but in your app with writeMessage/sendCommand (send message with presskey (volup/voldown), release key)
```javascript
monitor.WriteMessage(CEC.LogicalAddress.BROADCAST, CEC.LogicalAddress.AUDIOSYSTEM, CEC.Opcode.USER_CONTROL_PRESSED, CEC.UserControlCode.VOLUME_UP);
monitor.WriteMessage(CEC.LogicalAddress.BROADCAST, CEC.LogicalAddress.AUDIOSYSTEM, CEC.Opcode.USER_CONTROL_RELEASE);
monitor.WriteMessage(CEC.LogicalAddress.BROADCAST, CEC.LogicalAddress.AUDIOSYSTEM, CEC.Opcode.USER_CONTROL_PRESSED, CEC.UserControlCode.VOLUME_DOWN);
monitor.WriteMessage(CEC.LogicalAddress.BROADCAST, CEC.LogicalAddress.AUDIOSYSTEM, CEC.Opcode.USER_CONTROL_RELEASE);
```
Check if your soundbar is compatible and if cec is enabled. An then, please, confirm that with brand and model.

thanks

**Comment by pablodgonzalez** [comment]
I close this thread because there is no news.
