### ISSUE TITLE
eslint configuration not included in git repo

### ISSUE THREAD

**Issue by damoclark** [senzil/cec-monitor#2]
Hi Pablo,

I've opened a git clone of your code and while eslint is included in your dev toolchain, you haven't committed your eslint config to the repo.  

If you could do this, then I can ensure any PR I issue will be properly formatted. :)

Damien.

**Comment by pablodgonzalez** [comment]
Hi @damoclark, Thanks for the pull requests.
We are using the defaults values of eslint, nevertheless is a good idea freeze the config in the repo.
plese give a few days to review the PRs.
Thanks! Good Work!

**Comment by damoclark** [comment]
Hey @pablodgonzalez,

No problem.  Thanks for sharing your library.  

I'm adding features that I need for my use case, but it may not align with your future intentions.  If anything in my PRs is contrary to your long term intent for cec-monitor, let me know.  Happy to adapt accordingly.

Cheers,
Damo.

**Comment by pablodgonzalez** [comment]
@damoclark I've committed the eslint config.
I'm go to seeing your PR today
